controllers/AddAnnouncementController.php
<?php

namespace app\controllers;

use \app\models\Announcement;
use \app\models\Category;
use \app\models\Province;
use \app\models\FormCaptcha;
use \app\models\Measurementunit;
use \yii\helpers\Url;
use app\models\Subcategory;
use yii\helpers\Json;
use yii\web\UploadedFile;
use Yii;

class AddAnnouncementController extends \yii\web\Controller {

    public function actionIndex() {
        $categories = Category::find()->orderBy('name')->all();

        foreach ($categories as $c) {
            $menu[] = array('label' => $c->name, 'url' => ['announcement/index', 'categoryid' => $c->id]);
        }


        $announcements = new Announcement();
        $categories = new Category();
        $provinces = new Province();
        $measurementUnit = new Measurementunit();
        $catlist = $categories->find()->select(['name', 'id'])->indexBy('id')->orderBy('name')->column();
        $provincelist = $provinces->find()->select(['name', 'id'])->indexBy('id')->orderBy('name')->column();
        $unitlist = $measurementUnit->find()->select(['name', 'id'])->indexBy('id')->orderBy('name')->column();
        $formCaptha = new FormCaptcha();

        if (\Yii::$app->request->post()) {
            if ($announcements->load(\Yii::$app->request->post()) && $formCaptha->load(\Yii::$app->request->Post()) && $formCaptha->validate()) {
                $announcements->active = 0;
                $announcements->token = \Yii::$app->security->generateRandomString(20);
                if ($announcements->validate()) {
                    $announcements->imageFile = UploadedFile::getInstance($announcements, 'imageFile');

                    if (isset($announcements->imageFile)) {
                        $fileName = hash('md5', $announcements->imageFile->baseName . date('Y-m-d H:i:s')) . '.' . $announcements->imageFile->extension;
                        $announcements->imageFile->saveAs('uploads/' . $fileName);

                        $announcements->imageFile = $fileName;
                    } else {
                        $announcements->imageFile = 'no_image.png';
                    }
                    $announcements->save(false);

                    $this->sendMail($announcements->id, $announcements->token, $announcements->email);
                    
                    $session = Yii::$app->session;
                    $session->setFlash('message', 'Twoje ogłoszenie zostało dodane do bazy danych i oczekuje na akceptację moderatora. <br /> '
                            . 'Jeśli chcesz zmienić lub usunąć dodane ogłoszenie, sprawdź wiadomośc wysłaną na podany adres email: ' . $announcements->email);
                    $this->redirect(Url::toRoute(['announcement/index']));
                }
            }
        }


        return $this->render('index', [
                    'announcements' => $announcements,
                    'categories' => $categories,
                    'catlist' => $catlist,
                    'provincelist' => $provincelist,
                    'unitlist' => $unitlist,
                    'formCaptha' => $formCaptha,
                    'menuItems' => $menu
        ]);
    }

    public function actionSubcat() {

        if (\Yii::$app->request && ( \Yii::$app->request->isPost)) {
            $categoryId = \Yii::$app->request->Post()['depdrop_parents'];
            $subCat = Subcategory::find()->asArray()->select(['id', 'name'])->where(['categoryid' => $categoryId])->orderBy('name')->all();
            //if (\Yii::$app->request->isGet)
            $subCatId = \Yii::$app->request->get('subCatId');
            echo Json::encode(['output' => $subCat, 'selected' => isset($subCatId) ? $subCatId : '']);
            return;
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    protected function sendMail($id, $token, $to) {
        Yii::$app->mailer->compose('addAnnouncement', [
                    'id' => $id,
                    'token' => $token,
                ])
                ->setFrom(['info@agrobook24.pl' => 'agrobook24.pl'])
                ->setTo($to)
                ->setSubject('Gratulacje! Dodałeś nowe ogłoszenie.')
                ->send();
    }

    //public function actions() {
    //    return [
    //        'captcha' => [
    //            'class' => 'yii\captcha\CaptchaAction',
    //        ],
    //    ];
    //}
}

controllers/AnnouncementController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Category;
use app\models\Announcement;
use app\models\Subcategory;
use app\models\Province;
use app\models\Measurementunit;
use app\models\LoginForm;
use app\models\SignupForm;
use app\models\PageRules;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;
use yii\web\UploadedFile;
use yii\web\NotFoundHttpException;
use yii\helpers\ArrayHelper;
use yii\filters\AccessControl;
use \app\models\FormCaptcha;

class AnnouncementController extends \yii\web\Controller {

    public function actionIndex() {

        $added = Yii::$app->request->Get('added');
        //return Url::current();
        $announcementModel = new Announcement();
        $announcementModel->load(Yii::$app->request->Get());

        $measurementUnit = new Measurementunit();
        $unitlist = $measurementUnit->find()->select(['shortName', 'id'])->indexBy('id')->column();

        //--------------------KATEGORIE---------------------------
        $categories = Category::find()->orderBy('name')->all();

        foreach ($categories as $c) {
            $menu[] = array('label' => $c->name, 'url' => ['announcement/index', 'Announcement[categoryId]' => $c->id], 'active' => $announcementModel->categoryId == $c->id ? true : false);
        }

        $subcategoryMap = ArrayHelper::map(Subcategory::findAvailibleSubcategories($announcementModel), 'id', 'name');
        $provinceMap = ArrayHelper::map(Province::findAvailibleProvinces($announcementModel), 'id', 'name');

        //$query->andFilterWhere(['active' => 1]);

        $announcements = new ActiveDataProvider([
            'query' => Announcement::findByModel($announcementModel)->andFilterWhere(['active' => 1]), //->joinWith(['subcategory', 'category', 'province']),
            'pagination' => [
                'pageSize' => 10
            ],
            'sort' => ['defaultOrder' => ['date' => SORT_DESC]]
        ]);

        return $this->render('index', [
                    'announcements' => $announcements,
                    'menuItems' => $menu,
                    'subcategoryMap' => $subcategoryMap,
                    'added' => $added,
                    'announcementModel' => $announcementModel,
                    'provinceMap' => $provinceMap,
                    'unitlist' => $unitlist,
        ]);
    }

    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['admin-rbac']
                    ],
                ]
            ],
                /* [
                  'class' => 'yii\filters\PageCache',
                  'only' => ['index'],
                  'duration' => 0,
                  //         'varyByRoute' => false,
                  //      'dependency' => [
                  //        'class' => 'yii\caching\DbDependency',
                  //        'sql' => 'SELECT MAX(date) FROM announcement',
                  //],
                  'variations' => [
                  md5(Url::current() . (Yii::$app->user->isGuest ? 'aguest' : 'alogin')),
                  //$_GET['Announcement']['subcategoryid'],
                  //Yii::$app->request->Get(),
                  //(isset($_GET['categoryid'])) ? $_GET['categoryid'] : '',
                  //(isset($_GET['Announcement'])) ? $_GET['Announcement'] : '',
                  //(isset($_GET['id']))? $_GET['id'] : ''
                  ]
                  ], */
        ];
    }

    public function actionSignup() {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing Announcement model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id, $token) {
        $model = $this->findModel($id);
        if ($model->token != $token) {
            throw new \yii\web\NotFoundHttpException();
        }

        $formCaptha = new FormCaptcha();
        $oldImage = $model->imageFile;

        if (\Yii::$app->request->post() && $formCaptha->load(\Yii::$app->request->Post()) && $formCaptha->validate()) {
            if ($model->load(\Yii::$app->request->post()) && $model->validate()) {
                $model->imageFile = UploadedFile::getInstance($model, 'imageFile');

                if (isset($model->imageFile)) {
                    $fileName = hash('md5', $model->imageFile->baseName . date('Y-m-d H:i:s')) . '.' . $model->imageFile->extension;
                    $model->imageFile->saveAs('uploads/' . $fileName);
                    $model->imageFile = $fileName;
                } else {
                    if ($model->image != 'delete') {
                        $model->imageFile = $oldImage;
                    } else {
                        $model->imageFile = 'no_image.png';
                        if ($oldImage != 'no_image.png') {
                            unlink(Yii::$app->basePath . '/web/uploads/' . $oldImage);
                        }
                    }
                }
                $model->active = 0;
                if ($model->save()) {
                    return $this->redirect(['index']);
                }
            }
            //print_r($model);
        } else {
            $categories = new Category();
            $provinces = new Province();
            $measurementUnit = new Measurementunit();
            $catlist = $categories->find()->select(['name', 'id'])->indexBy('id')->orderBy('name')->column();
            $provincelist = $provinces->find()->select(['name', 'id'])->indexBy('id')->orderBy('name')->column();
            $unitlist = $measurementUnit->find()->select(['name', 'id'])->indexBy('id')->orderBy('name')->column();
            $formCaptha = new FormCaptcha();


            return $this->render('../add-announcement/_form', [
                        'announcements' => $model,
                        'categories' => $categories,
                        'catlist' => $catlist,
                        'provincelist' => $provincelist,
                        'unitlist' => $unitlist,
                        'formCaptha' => $formCaptha,
            ]);
        }
    }

    /**
     * Deletes an existing Announcement model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id, $token) {
        $model = $this->findModel($id);

        if ($model->token != $token) {
            throw new \yii\web\NotFoundHttpException();
        }
        if ($model->imageFile != 'no_image.png') {
            unlink(Yii::$app->basePath . '/web/uploads/' . $model->imageFile);
        }
        $model->delete();


        return $this->redirect(['index']);
    }
    
    public function actionHowDoesItWork() {
        return $this->render('howdoesitwork');
    }

    public function actionRules() {
        $model = PageRules::find()->one();
        return $this->render('rules', [
                        'model' => $model,
            ]);
    }
    
    /**
     * Finds the Announcement model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Announcement the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Announcement::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actions() {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

}

views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\assets\AppAsset;
use yii\bootstrap\NavBar;
use yii\bootstrap\Nav;
use app\assets\AjaxAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <?= Html::csrfMetaTags() ?>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="<?php echo Yii::$app->request->baseUrl . '/uploads'; ?>/favicon.ico" type="image/x-icon" />
        <title><?= Html::encode($this->title) ?></title>
        <meta name="keywords" content="giełda rolna, giełda, rolnictwo, owoce, warzywa, ziemniaki, zboża, ogłoszenia, sprzedam, kupię, rzepak, rolnik">

        <?php $this->head(); ?>
        <?php
        if (Yii::$app->user->isGuest) {
            AjaxAsset::register($this);
            ?>
            <script>
                (function (i, s, o, g, r, a, m) {
                    i['GoogleAnalyticsObject'] = r;
                    i[r] = i[r] || function () {
                        (i[r].q = i[r].q || []).push(arguments)
                    }, i[r].l = 1 * new Date();
                    a = s.createElement(o),
                            m = s.getElementsByTagName(o)[0];
                    a.async = 1;
                    a.src = g;
                    m.parentNode.insertBefore(a, m)
                })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

                ga('create', 'UA-55231959-4', 'auto');
                ga('send', 'pageview');

            </script>
<?php } ?>
    </head>
    <body>
<?php $this->beginBody() ?>

        <div class="container" id="container">

            <div class="row">
                <div class="col-xs-12 col-sm-12">
                    <?php NavBar::begin(['brandLabel' => '<img src="' . Yii::$app->request->baseUrl . '/uploads/logo.png" style="width: 160px; position: relative; bottom: 10px" />', 'options' => ['class' => 'navbar navbar-default navbar-fixed-top']]); ?>
                    <?=
                    Nav::widget([
                        'items' => [
                            ['label' => 'HOME', 'url' => ['announcement/index']],
                            ['label' => 'JAK TO DZIAŁA', 'url' => ['/announcement/how-does-it-work']],
                            ['label' => 'DODAJ OGŁOSZENIE', 'url' => ['/add-announcement/index'], 'options' => ['style' => 'background-color: #B02B2C;']],
                            !Yii::$app->user->isGuest ?
                                    [
                                'label' => '<img src="/uploads/anonuser.png" class="user-image" alt="User Image" style="width:20px; border-radius: 50%; margin-right: 10px; margin-top:-2px">' . mb_strtoupper(Yii::$app->user->identity->username),
                                'encodeLabels' => false,
                                'items' => [
                                    Yii::$app->user->can('admin') ? ['label' => 'PANEL ADMINISTRACYJNY', 'url' => ['/admin']] : '',
                                    ['label' => 'WYLOGUJ', 'url' => ['/announcement/logout']],
                                ],
                                    ] : '',
                        ],
                        'options' => ['class' => 'navbar-nav'],
                        'encodeLabels' => false,
                    ]);
                    ?>
                    <?php NavBar::end(); ?>
                </div>
            </div>
            <div id="middle">
                <?= $content
                ?>
            </div>

            <div id="footer" class="row">
                <span style="margin-right: 30px;"><?= Html::a("Regulamin", ['/announcement/rules']); ?></span>
                <span>Copyright © 2016 AgroBook24.pl</span>
            </div>
        </div>


        <?php $this->endBody() ?>
    </body>

</html>
<?php $this->endPage() ?>

views/layouts/main_admin_old.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\assets\AppAsset;
use yii\bootstrap\NavBar;
use yii\bootstrap\Nav;
use app\models\Announcement;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <?= Html::csrfMetaTags() ?>
        <meta charset="<?= Yii::$app->charset ?>">
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head(); ?>

    </head>
    <body>
        <?php $this->beginBody() ?>

        <div class="container " >
            <div class="row">
                <div class="col-xs-9">
                    <?php NavBar::begin(['brandLabel' => 'HETA.PL', 'options' => ['class' => 'navbar navbar-default navbar-fixed-top']]); ?>
                    <?=
                    Nav::widget([
                        'items' => [
                            ['label' => 'PANEL ADMINISTRACYJNY', 'url' => ['/admin/announcement/index'], 'active' => true,],
                            !Yii::$app->user->isGuest ? ['label' => 'WYLOGUJ', 'url' => ['/announcement/logout']] : '',
                        ],
                        //'route' => '/admin/',
                        'options' => ['class' => 'navbar-nav'],
                    ]);
                    ?>
                    <?php NavBar::end(); ?>
                </div>
            </div><br /><br /><br /><br />
            <div class="row">
                <div class="col-xs-2">
                    <span class="categoryText">Ustawienia</span> <br />
<?php
echo Nav::widget([
    'items' => [
        ['label' => 'Ogólne', 'url' => ['category/index3']],
        ['label' => 'Statystyki', 'url' => ['subcategory/index22']],
        ['label' => 'Złote myśli', 'url' => ['subcategory/index22']],
    ],
    'route' => Yii::$app->controller->id . '/index',
    //'route' => 'announcement/index',
    //'params' => ['categoryid'],
    //'options' => ['class' =>'btn-group-vertical', 'role' => 'group']
    //'options' => ['role' => 'navigation']
    'options' => ['class' => 'nav-pills nav-stacked categoryLinks', 'role' => 'navigation'],
]);
?>
                    <br />
                    <?php if (Yii::$app->user->can('admin-rbac')) { ?>
                        <span class="categoryText">RBAC</span> <br />
                        <?php
                        echo Nav::widget([
                            'items' => [
                                ['label' => 'Użytkownicy', 'url' => ['/rbac/user'], 'active' => Yii::$app->controller->id == 'user' ? true : false],
                                ['label' => 'Powiązania', 'url' => ['/rbac/assignment'], 'active' => Yii::$app->controller->id == 'assignment' ? true : false],
                                ['label' => 'Role', 'url' => ['/rbac/role'], 'active' => Yii::$app->controller->id == 'role' ? true : false],
                                ['label' => 'Uprawnienia', 'url' => ['/rbac/permission'], 'active' => Yii::$app->controller->id == 'permission' ? true : false],
                                ['label' => 'Ścieżki', 'url' => ['/rbac/route'], 'active' => Yii::$app->controller->id == 'route' ? true : false],
                                ['label' => 'Reguły', 'url' => ['/rbac/rule'], 'active' => Yii::$app->controller->id == 'rule' ? true : false],
                            ],
                            //'route' => Yii::$app->controller->id.'/index',
                            //'route' => 'announcement/index',
                            //'params' => ['categoryid'],
                            //'options' => ['class' =>'btn-group-vertical', 'role' => 'group']
                            //'options' => ['role' => 'navigation']
                            'options' => ['class' => 'nav-pills nav-stacked categoryLinks', 'role' => 'navigation'],
                        ]);
                        ?>
                        <br />
                    <?php } ?>
                    <span class="categoryText">MENU</span> <br />
                    <?php
                    echo Nav::widget([
                        'items' => [
                            ['label' => 'Kategorie', 'url' => ['/admin/category/index']],
                            ['label' => 'Podkategorie', 'url' => ['/admin/subcategory/index']],
                            ['label' => 'Województwa', 'url' => ['/admin/province/index']],
                        ],
                        'route' => Yii::$app->controller->id . '/index',
                        //'route' => 'announcement/index',
                        //'params' => ['categoryid'],
                        //'options' => ['class' =>'btn-group-vertical', 'role' => 'group']
                        //'options' => ['role' => 'navigation']
                        'options' => ['class' => 'nav-pills nav-stacked categoryLinks', 'role' => 'navigation'],
                    ]);
                    ?>
                    <br />
                    <span class="categoryText">Ogłoszenia</span> <br />
                    <?php
                    $badge = 'Akceptuj<span class="badge">' . Announcement::find()->where(['active' => '0'])->count() . '<span>';
                    echo Nav::widget([
                        'encodeLabels' => false,
                        'items' => [
                            ['label' => 'Edycja', 'url' => ['/admin/announcement/index']],
                            ['label' => $badge, 'url' => ['/admin/announcement/acceptation'], 'encode' => false],
                            ['label' => 'Archiwum', 'url' => ['subcategory/index23']],
                            
                        ],
                        'route' => Yii::$app->controller->id . '/' .Yii::$app->controller->action->id,
                        //'route' => 'announcement/index',
                        //'params' => ['categoryid'],
                        //'options' => ['class' =>'btn-group-vertical', 'role' => 'group']
                        //'options' => ['role' => 'navigation']
                        'options' => ['class' => 'nav-pills nav-stacked categoryLinks', 'role' => 'navigation'],
                    ]);
                    ?>
                    <br />
                </div>
                <div class="col-xs-10">
<?= $content
?>
                </div>
            </div>
        </div>

<?php $this->endBody() ?>
    </body>
</html>
        <?php $this->endPage() ?>