controllers/AddAnnouncementController.php
<?php

namespace app\controllers;

use \app\models\Announcement;
use \app\models\Category;
use \app\models\Province;
use \app\models\FormCaptcha;
use \app\models\Measurementunit;
use \yii\helpers\Url;
use app\models\Subcategory;
use yii\helpers\Json;
use yii\web\UploadedFile;
use Yii;

class AddAnnouncementController extends \yii\web\Controller {

    public function actionIndex() {
        $categories = Category::find()->orderBy('name')->all();

        foreach ($categories as $c) {
            $menu[] = array('label' => $c->name, 'url' => ['announcement/index', 'categoryid' => $c->id]);
        }


        $announcements = new Announcement();
        $categories = new Category();
        $provinces = new Province();
        $measurementUnit = new Measurementunit();
        $catlist = $categories->find()->select(['name', 'id'])->indexBy('id')->orderBy('name')->column();
        $provincelist = $provinces->find()->select(['name', 'id'])->indexBy('id')->orderBy('name')->column();
        $unitlist = $measurementUnit->find()->select(['name', 'id'])->indexBy('id')->orderBy('name')->column();
        $formCaptha = new FormCaptcha();

        if (\Yii::$app->request->post()) {
            if ($announcements->load(\Yii::$app->request->post()) && $formCaptha->load(\Yii::$app->request->Post()) && $formCaptha->validate()) {
                $announcements->active = 0;
                $announcements->token = \Yii::$app->security->generateRandomString(20);
                if ($announcements->validate()) {
                    $announcements->imageFile = UploadedFile::getInstance($announcements, 'imageFile');

                    if (isset($announcements->imageFile)) {
                        $fileName = hash('md5', $announcements->imageFile->baseName . date('Y-m-d H:i:s')) . '.' . $announcements->imageFile->extension;
                        $announcements->imageFile->saveAs('uploads/' . $fileName);

                        $announcements->imageFile = $fileName;
                    } else {
                        $announcements->imageFile = 'no_image.png';
                    }
                    $announcements->save(false);

                    $this->sendMail($announcements->id, $announcements->token, $announcements->email);
                    
                    $session = Yii::$app->session;
                    $session->setFlash('message', 'Twoje ogłoszenie zostało dodane do bazy danych i oczekuje na akceptację moderatora. <br /> '
                            . 'Jeśli chcesz zmienić lub usunąć dodane ogłoszenie, sprawdź wiadomośc wysłaną na podany adres email: ' . $announcements->email);
                    $this->redirect(Url::toRoute(['announcement/index']));
                }
            }
        }


        return $this->render('index', [
                    'announcements' => $announcements,
                    'categories' => $categories,
                    'catlist' => $catlist,
                    'provincelist' => $provincelist,
                    'unitlist' => $unitlist,
                    'formCaptha' => $formCaptha,
                    'menuItems' => $menu
        ]);
    }

    public function actionSubcat() {

        if (\Yii::$app->request && ( \Yii::$app->request->isPost)) {
            $categoryId = \Yii::$app->request->Post()['depdrop_parents'];
            $subCat = Subcategory::find()->asArray()->select(['id', 'name'])->where(['categoryid' => $categoryId])->orderBy('name')->all();
            //if (\Yii::$app->request->isGet)
            $subCatId = \Yii::$app->request->get('subCatId');
            echo Json::encode(['output' => $subCat, 'selected' => isset($subCatId) ? $subCatId : '']);
            return;
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    protected function sendMail($id, $token, $to) {
        Yii::$app->mailer->compose('addAnnouncement', [
                    'id' => $id,
                    'token' => $token,
                ])
                ->setFrom(['info@agrobook24.pl' => 'agrobook24.pl'])
                ->setTo($to)
                ->setSubject('Gratulacje! Dodałeś nowe ogłoszenie.')
                ->send();
    }

    //public function actions() {
    //    return [
    //        'captcha' => [
    //            'class' => 'yii\captcha\CaptchaAction',
    //        ],
    //    ];
    //}
}

controllers/AnnouncementController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Category;
use app\models\Announcement;
use app\models\Subcategory;
use app\models\Province;
use app\models\Measurementunit;
use app\models\LoginForm;
use app\models\SignupForm;
use app\models\PageRules;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;
use yii\web\UploadedFile;
use yii\web\NotFoundHttpException;
use yii\helpers\ArrayHelper;
use yii\filters\AccessControl;
use \app\models\FormCaptcha;

class AnnouncementController extends \yii\web\Controller {

    public function actionIndex() {

        $added = Yii::$app->request->Get('added');
        //return Url::current();
        $announcementModel = new Announcement();
        $announcementModel->load(Yii::$app->request->Get());

        $measurementUnit = new Measurementunit();
        $unitlist = $measurementUnit->find()->select(['shortName', 'id'])->indexBy('id')->column();

        //--------------------KATEGORIE---------------------------
        $categories = Category::find()->orderBy('name')->all();

        foreach ($categories as $c) {
            $menu[] = array('label' => $c->name, 'url' => ['announcement/index', 'Announcement[categoryId]' => $c->id], 'active' => $announcementModel->categoryId == $c->id ? true : false);
        }

        $subcategoryMap = ArrayHelper::map(Subcategory::findAvailibleSubcategories($announcementModel), 'id', 'name');
        $provinceMap = ArrayHelper::map(Province::findAvailibleProvinces($announcementModel), 'id', 'name');

        //$query->andFilterWhere(['active' => 1]);

        $announcements = new ActiveDataProvider([
            'query' => Announcement::findByModel($announcementModel)->andFilterWhere(['active' => 1]), //->joinWith(['subcategory', 'category', 'province']),
            'pagination' => [
                'pageSize' => 10
            ],
            'sort' => ['defaultOrder' => ['date' => SORT_DESC]]
        ]);

        return $this->render('index', [
                    'announcements' => $announcements,
                    'menuItems' => $menu,
                    'subcategoryMap' => $subcategoryMap,
                    'added' => $added,
                    'announcementModel' => $announcementModel,
                    'provinceMap' => $provinceMap,
                    'unitlist' => $unitlist,
        ]);
    }

    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['admin-rbac']
                    ],
                ]
            ],
                /* [
                  'class' => 'yii\filters\PageCache',
                  'only' => ['index'],
                  'duration' => 0,
                  //         'varyByRoute' => false,
                  //      'dependency' => [
                  //        'class' => 'yii\caching\DbDependency',
                  //        'sql' => 'SELECT MAX(date) FROM announcement',
                  //],
                  'variations' => [
                  md5(Url::current() . (Yii::$app->user->isGuest ? 'aguest' : 'alogin')),
                  //$_GET['Announcement']['subcategoryid'],
                  //Yii::$app->request->Get(),
                  //(isset($_GET['categoryid'])) ? $_GET['categoryid'] : '',
                  //(isset($_GET['Announcement'])) ? $_GET['Announcement'] : '',
                  //(isset($_GET['id']))? $_GET['id'] : ''
                  ]
                  ], */
        ];
    }

    public function actionSignup() {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing Announcement model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id, $token) {
        $model = $this->findModel($id);
        if ($model->token != $token) {
            throw new \yii\web\NotFoundHttpException();
        }

        $formCaptha = new FormCaptcha();
        $oldImage = $model->imageFile;

        if (\Yii::$app->request->post() && $formCaptha->load(\Yii::$app->request->Post()) && $formCaptha->validate()) {
            if ($model->load(\Yii::$app->request->post()) && $model->validate()) {
                $model->imageFile = UploadedFile::getInstance($model, 'imageFile');

                if (isset($model->imageFile)) {
                    $fileName = hash('md5', $model->imageFile->baseName . date('Y-m-d H:i:s')) . '.' . $model->imageFile->extension;
                    $model->imageFile->saveAs('uploads/' . $fileName);
                    $model->imageFile = $fileName;
                } else {
                    if ($model->image != 'delete') {
                        $model->imageFile = $oldImage;
                    } else {
                        $model->imageFile = 'no_image.png';
                        if ($oldImage != 'no_image.png') {
                            unlink(Yii::$app->basePath . '/web/uploads/' . $oldImage);
                        }
                    }
                }
                $model->active = 0;
                if ($model->save()) {
                    return $this->redirect(['index']);
                }
            }
            //print_r($model);
        } else {
            $categories = new Category();
            $provinces = new Province();
            $measurementUnit = new Measurementunit();
            $catlist = $categories->find()->select(['name', 'id'])->indexBy('id')->orderBy('name')->column();
            $provincelist = $provinces->find()->select(['name', 'id'])->indexBy('id')->orderBy('name')->column();
            $unitlist = $measurementUnit->find()->select(['name', 'id'])->indexBy('id')->orderBy('name')->column();
            $formCaptha = new FormCaptcha();


            return $this->render('../add-announcement/_form', [
                        'announcements' => $model,
                        'categories' => $categories,
                        'catlist' => $catlist,
                        'provincelist' => $provincelist,
                        'unitlist' => $unitlist,
                        'formCaptha' => $formCaptha,
            ]);
        }
    }

    /**
     * Deletes an existing Announcement model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id, $token) {
        $model = $this->findModel($id);

        if ($model->token != $token) {
            throw new \yii\web\NotFoundHttpException();
        }
        if ($model->imageFile != 'no_image.png') {
            unlink(Yii::$app->basePath . '/web/uploads/' . $model->imageFile);
        }
        $model->delete();


        return $this->redirect(['index']);
    }
    
    public function actionHowDoesItWork() {
        return $this->render('howdoesitwork');
    }

    public function actionRules() {
        $model = PageRules::find()->one();
        return $this->render('rules', [
                        'model' => $model,
            ]);
    }
    
    /**
     * Finds the Announcement model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Announcement the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Announcement::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actions() {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

}

views/add-announcement/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\widgets\MaskedInput;
use yii\captcha\Captcha;
use kartik\widgets\DepDrop;
use kartik\widgets\FileInput;
use kartik\widgets\Select2;
?>
<?php
$form = ActiveForm::begin([
            'id' => 'login-form',
            'options' => ['class' => 'form-horizontal', 'enctype' => 'multipart/form-data'],
        ])
?>
<?php if (Yii::$app->controller->id == "add-announcement") { ?>
    <div class="well" style="font-size: 12px; border-left: solid #8ebb5b 6px;">

        <span style="font-size: 14px; color: #3e6636; margin-bottom: 6px;"><strong>Dobra robota!</strong></span> <br />Już tylko kilka minut dzieli Cię od dodania własnego ogłoszenia. Ale pamiętaj! <strong>Nasz klient - nasz Pan.</strong> Dlatego postaraj się trochę.
        Ogłoszenia niespójne, niekompletne, z błędami - nie będą akceptowane. Szanujmy czas naszych klientów.
    </div>

<?php } ?>
<div class="row">
    <div class="col-lg-8 col-md-7 col-sm-12 col-xs-12">
        <?= $form->field($announcements, 'title')->textInput(['style' => 'width:95%']); ?>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-6 col-xs-6">
        <?php //echo $form->field($announcements, 'categoryId')->dropDownList($catlist, ['prompt' => 'Wybierz', 'style' => 'width:150px']);
        ?>

        <?php
        echo $form->field($announcements, 'categoryId')->widget(Select2::classname(), [
            'data' => $catlist,
            'options' => ['placeholder' => 'Wybierz'],
            'pluginOptions' => [
                'width' => '95%',
            ]
        ]);
        ?>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-6 col-xs-6">
        <?=
        $form->field($announcements, 'subcategoryid')->widget(DepDrop::className(), [
            'type' => DepDrop::TYPE_SELECT2,
            'pluginOptions' => [
                'depends' => [Html::getInputId($announcements, 'categoryId')], // the id for cat attribute
                'initialize' => isset($announcements->subcategoryid) ? true : false,
                'initDepends' => [Html::getInputId($announcements, 'categoryId')],
                'placeholder' => 'Wybierz',
                'url' => Url::to(['add-announcement/subcat', 'subCatId' => $announcements->subcategoryid]),
            ],
            'select2Options' => [
                'pluginOptions' => [
                    'width' => '95%',
                ]
            ],
        ]);
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-2 col-md-3 col-sm-8 col-xs-8">
        <?= $form->field($announcements, 'minimumOrder')->textInput(['style' => 'width:95%']); ?>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4">
        <?php
        echo $form->field($announcements, 'minimumOrderUnitId')->widget(Select2::classname(), [
            'data' => $unitlist,
            'options' => ['placeholder' => 'Wybierz'],
            'pluginOptions' => [
                'width' => '95%',
            ]
        ]);
        ?>
    </div>
    <div class="col-lg-4 col-md-2 visible-lg-inline visible-md-inline"></div>
    <div class="col-lg-2 col-md-3 col-sm-8 col-xs-8">
        <?=
        $form->field($announcements, 'price')->textInput()->widget(MaskedInput::className(), [
            //'mask' => '9{1,10}.99',
            'clientOptions' => [
                //'mask' => '9{1,10}.99',
                'alias' => 'currency',
                'prefix' => '',
                'groupSeparator' => '',
                'autoGroup' => true
            ],
            'options' => ['style' => 'width:95%', 'class' => 'form-control'],
        ])->label("Cena (zł)")
        ?>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4">
        <?php
        echo $form->field($announcements, 'priceUnitId')->widget(Select2::classname(), [
            'data' => $unitlist,
            'options' => ['placeholder' => 'Wybierz'],
            'pluginOptions' => [
                'width' => '95%',
            ]
        ]);
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <?= $form->field($announcements, 'content')->textarea(['style' => 'height:200px']); ?>

    </div>
    <div class="col-lg-12">
        <?php if (Yii::$app->controller->id == "add-announcement") { ?>

            <div class="well" style="font-size: 12px; border-left: solid #8ebb5b 6px;">

                Dodanie zdjęcia nie jest obowiązkowe. <strong>Ale cóż lepiej przyciągnie uwagę od genialnego zdjęcia,</strong> naszego jeszcze bardziej genialnego produktu?
            </div>
        <?php } ?>
        <?=
        $form->field($announcements, 'imageFile')->widget(FileInput::classname(), [
            'options' => ['accept' => 'image/*', 'multiple' => false],
            'pluginOptions' => [
                'removeClass' => 'btn btn-danger',
                'showUpload' => false,
                'allowedFileExtensions' => ['jpg', 'gif', 'png'],
                'initialPreview' => isset($announcements->imageFile) && !empty($announcements->imageFile) ?
                        [
                    Html::img("@web/uploads/{$announcements->imageFile}", ['class' => 'file-preview-image', 'alt' => $announcements->title, 'title' => $announcements->title]),
                        ] : '',
                'initialCaption' => isset($announcements->imageFile) ? $announcements->imageFile : '',
                'initialPreviewShowDelete' => true,
                'overwriteInitial' => true,
            ],
            'pluginEvents' =>
            [
                'fileclear' => "function(event, key) {
                    $('#announcement-image').val(\"delete\");
                }",
            ]
        ]);
        ?>
    </div>
</div>
<?php if (Yii::$app->controller->id == "add-announcement") { ?>
    <div class="well" style="font-size: 12px; border-left: solid #8ebb5b 6px;">

        <span style="font-size: 14px; color: #3e6636; margin-bottom: 6px;"><strong>Tak trzymaj!</strong></span> <br /> Już prawie skończyliśmy. Dodaj jeszcze tylko informacje o sobie - aby kontrahenci mogili się z Tobą skontaktować - <strong>i gotowe!</strong>
    </div>
<?php } ?>
<div class="row">
    <div class="col-lg-9 col-md-9">
        <?= $form->field($announcements, 'advertiser')->textInput(['style' => 'width:95%']); ?>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
        <?php
        echo $form->field($announcements, 'provinceId')->widget(Select2::classname(), [
            'data' => $provincelist,
            'options' => ['placeholder' => 'Wybierz'],
            'pluginOptions' => [
                'width' => '95%',
            ]
        ]);
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-2 col-md-3 col-sm-5 col-xs-5">
        <?=
        $form->field($announcements, 'phoneNumber')->widget(MaskedInput::className(), [
            'mask' => '999-999-999',
            'options' => ['style' => 'width:95%', 'class' => 'form-control'],
        ])
        ?>
    </div>   
    <div class="col-lg-3 col-md-4 col-sm-7 col-xs-7">
        <?=
        $form->field($announcements, 'email')->widget(MaskedInput::className(), [
            'clientOptions' => [
                'alias' => 'email'
            ],
            'options' => ['style' => 'width:95%', 'class' => 'form-control'],
        ])
        ?>
    </div>   
</div>

<?php echo $form->field($announcements, 'image')->hiddenInput()->label(false); ?>


<div class="row">
    <?php if (Yii::$app->controller->id == "add-announcement" || "announcement") { ?>
        <div class="col-lg-12">
            <?php //echo $form->field($formCaptha, 'captcha')->textInput()->widget(Captcha::className(), ['template' => '{image}{input}', 'options' => ['style' => 'width:300px', 'class' => 'form-control']]); ?>
            <?=
            $form->field($formCaptha, 'captcha')->widget(
                    \himiklab\yii2\recaptcha\ReCaptcha::className(), ['siteKey' => '6LdhBiETAAAAAHpUZGg0cKLTjl16WA917caYrLk6']
            )->label('');
            ?>

        </div>
    <?php } ?>

    
        <div class="col-lg-12 col-xs-10">
            <?= Html::submitButton((Yii::$app->controller->id == "add-announcement" || "announcement") ? 'Dodaj' : 'Zapisz', ['class' => 'btn btn-primary']) ?>
            <?=
            Yii::$app->controller->id == "announcement" ?
                    Html::a('Usuń ogłoszenie', ['announcement/delete'], [
                        'data' => [
                            'method' => 'get',
                            'confirm' => 'Czy jesteś pewien, że chcesz usunąć ogłoszenie??',
                            'params' => ['id' => $announcements->id, 'token' => $announcements->token],
                        ],
                        'class' => 'btn btn-primary'
                    ]) : '';
            ?>
        </div>
    
</div>


<?php ActiveForm::end() ?>

views/add-announcement/index.php
<?php
/* @var $this yii\web\View */
/* @var $categories \app\models\Category */

use yii\bootstrap\Nav;
$this->title = 'agrobook24.pl - Giełda Rolna - Dodaj ogłoszenie'; 
\Yii::$app->view->registerMetaTag([
        'name' => 'description',
        'content' => 'Dodaj nowy produkt i bądź widoczny w największej internetowej giełdzie rolnej AgroBook24.pl. Z nami sprzedawanie staje się proste!',
    ]);
?>
<div class="row">
    <div class="col-lg-2 col-md-2 col-sm-2 visible-lg-inline visible-md-inline visible-sm-inline">
        <span class="categoryText">KATEGORIE</span> <br />
        <?php
        echo Nav::widget([
            'items' => $menuItems,
            //'route' => 'announcement/index',
            //'params' => ['categoryid'],
            //'options' => ['class' =>'btn-group-vertical', 'role' => 'group']
            //'options' => ['role' => 'navigation']
            'options' => ['class' => 'nav-pills nav-stacked categoryLinks', 'role' => 'navigation'],
        ]);
        ?>
        
    </div>
    <div class="col-xs-12 visible-xs-inline"><br/></div>
    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">

        <?=
        $this->render('_form', [
            'announcements' => $announcements,
            'categories' => $categories,
            'catlist' => $catlist,
            'provincelist' => $provincelist,
            'unitlist' => $unitlist,
            'formCaptha' => $formCaptha,
        ]);
        ?>


    </div>
</div>